# Generated by Django 5.0.1 on 2024-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_pizza_ingredients_alter_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('basico', 'Basico'), ('premium', 'Premium')], default='basic', max_length=7),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='state',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='active', max_length=8),
        ),
    ]
